import "./globals.css";

import type {Metadata} from "next";
import {Inter} from "next/font/google";
import React from "react";

import {FooterComponent, HeaderComponent} from "@/components";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
   title: "Dictionary App",
   description: "Generated by create next app",
};

type PropType = { children: React.ReactNode; }
export default function RootLayout({children}: Readonly<PropType>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <p>app layout</p>
            <HeaderComponent/>
            {children}
            <FooterComponent/>
            <p>app layout</p>
         </body>
      </html>
   );
}
