import "./globals.css";

import type {Metadata} from "next";
import {Mulish} from "next/font/google";
import React from "react";

import {FooterComponent, HeaderComponent} from "@/components";

const inter = Mulish({weight: "400", subsets: ["latin"]});

export const metadata: Metadata = {
   title: "Dictionary App",
   description: "Generated by create next app",
};

type PropType = { children: React.ReactNode; }
export default function RootLayout({children}: Readonly<PropType>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <div className={"bodyContainer"}>
               <HeaderComponent/>
               {children}
               <FooterComponent/>
            </div>
         </body>
      </html>
   );
}
